apps/calculate/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [

    # 返回通道信息
    url(r'^channellist/$', ChannelList.as_view()),

    # 返回算法结果
    url(r'^parse/$', CalculateParse.as_view()),

    # return_file_list
    url(r'file_list/', return_file_list),

    # auto_calculate
    url(r'auto/', auto_calculate),

    # 处理PPT
    url('^parse_ppt/$', PPTParse.as_view()),

    # 跳转扉页
    url('^test_page/$', test_page),

    # 手动报告
    url('^user_calculate/$', manual_report),

]

apps/users/urls.py
from .views import *
from django.conf.urls import url
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token

router = DefaultRouter()
router.register(r'^user', UserViewSet, basename="user")
router.register(r'^file', UserFileViewSet, basename="file")

app_name = "users"

urlpatterns = [

    url(r'^home/$', home, name="home"),

    url(r'^login/$', obtain_jwt_token, name="login"),

    url(r'^logout/$', LogoutView.as_view(), name="logout"),

]

urlpatterns += router.urls

epgn/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView, RedirectView
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    # 站点管理
    # url(r'^admin/', xadmin.site.urls, name="xadmin"),
    url(r'^admin/', admin.site.urls, name="admin"),

    # 显示图片的请求 ==> /favicon.ico
    url(r'^favicon\.ico$', RedirectView.as_view(url=r'static/image/favicon.ico')),

    # 这是直接访问IP时, 浏览器展示的页面 ==> templates文件夹中的文件
    # url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^$', TemplateView.as_view(template_name='user/login.html'), name='login'),

    url(r'^authorization/$', obtain_jwt_token),
    # url(r'^authorization/$', jwt_response_payload_handler),

    url(r'user/', include('users.urls'), name="users"),

    url(r'test/', include('fileinfo.urls'), name="test"),

    url(r'calculate/', include('calculate.urls'), name="calculate"),

    url(r'audio/', include('audio.urls'), name="audio"),

    url(r'bug/', include('bug.urls'), name="bug"),

    url(r'time/', include('worktime.urls'), name="time"),

    url(r'script/', include('script.urls'), name="script"),

    url(r'voice/', include('voice.urls'), name="voice"),
]

handler404 = 'script.views.pageNotFound'

# 修改admin中的标题
admin.site.site_title = "EPGN_INFO 后台管理"
admin.site.site_header = "EPGN_INFO"

apps/calculate/models.py
from django.db import models

# Create your models here.

apps/calculate/views.py
import json
import math
from pprint import pprint

import numpy as np
import pandas as pd
from time import time
from django.views import View
from scripts.parse_ppt import *
from django.shortcuts import render
from scripts.readHDF import read_hdf
from fileinfo.models import Fileinfo
from scripts.process_gecent import ParseTask
from scripts.segment import parse
from settings.dev import REFERENCE_CHANNEL, FALLING_LIST
from calculate.algorithm.class_name import CalculateNameList
from apps.calculate.algorithm.class_name import CalculateNameDict
from django.http import JsonResponse, HttpResponse, StreamingHttpResponse


# 处理通道信息： url(r'^channelList/$', ChannelList.as_view()),
class ChannelList(View):

    # 文件通道信息
    def put(self, request):
        body = request.body
        body_str = body.decode()
        data_list = json.loads(body_str)["file_info"]

        if data_list is None:
            return JsonResponse({"code": 1, "msg": "TypeError: 'NoneType' object is not iterable"})
        set_channel_list = []
        channel_dict_list = []
        num_1 = 1
        for file in data_list:
            file_channel_info = {}
            file_name = file["file_name"]
            channel_dict, items = read_hdf(file_name)
            channel_key_list = []

            for key, value in channel_dict.items():
                if value == "time" or value == "Time":
                    continue
                set_channel_list.append(value.replace(' ', ''))
                channel_key_list.append({"title": value.replace(' ', ''), "id": 1000 + num_1})
                # set_channel_list.append(value)
                # channel_key_list.append({"title": value, "id": 1000 + num_1})
                num_1 += 1

            file_channel_info["title"] = file_name
            file_channel_info["id"] = 10000 + num_1
            file_channel_info["spread"] = True
            file_channel_info["children"] = channel_key_list
            channel_dict_list.append(file_channel_info)
            num_1 += 1

        main_info = [{
            "title": "文件夹名",
            "id": 1,
            "field": 'name1',
            "checked": False,
            "spread": True,
            "children": channel_dict_list
        }]
        return JsonResponse({"file_info": main_info, "channel_list": list(set(set_channel_list))})

    # 通道去重
    def post(self, request):
        if request.method == "POST":
            body = request.body
            body_str = body.decode()
            data_list = json.loads(body_str)["file_info"]

            file_list = []
            set_channel_list = []
            for data in data_list:
                print(data)
                file_name = data["file_name"]
                file_list.append(file_name)
                channel_list, items = read_hdf(file_name)
                for values in channel_list.values():
                    if values not in set_channel_list:
                        set_channel_list.append(values)

            return JsonResponse({
                "channel_list": set_channel_list,
                "algorithm": CalculateNameList,
                "file_list": file_list
            })
        return HttpResponse("当前为POST请求，请检查请求方式！")


# 算法结果： url(r'^calculate/$', CalculateParse.as_view()),
class CalculateParse(View):

    def get(self, request):
        return render(request, 'calculate/calculate.html')

    # 通过算法返回数组数据
    def post(self, request):
        body = request.body
        body_str = body.decode()
        body_json = json.loads(body_str)
        result_data = []

        # params-->filename-->status-->rpm_type
        for file in body_json["file_info"]["children"]:
            rpm_type = 'rising'  # 先设置一个默认值
            filename = file["title"]
            status = Fileinfo.objects.filter(file_name=filename)
            if len(status) > 0:
                status = status[0].status
                if status in FALLING_LIST:
                    rpm_type = 'falling'
            else:
                print("PPTParse >> parse_calculate() 出错！")
                return JsonResponse({"code": 500, "msg": "获取工况出错！"})

            # 重构传入算法的通道信息
            channel_info_list = []
            for channel_info in body_json["file_info"]["children"][0]["children"]:
                if channel_info["title"] not in REFERENCE_CHANNEL:
                    channel_info_list.append(channel_info)
            body_json["file_info"]["children"][0]["children"] = channel_info_list

            items = ParseTask(body_json, rpm_type).user_run()
            for item in items:
                x_list = list(item["data"]["X"])
                y_list = list(item["data"]["Y"])
                line_loc = []
                for x, y in zip(x_list, y_list):
                    point_loc = []
                    try:
                        point_loc.append(math.log(abs(x), 10))
                    except:
                        continue
                    point_loc.append(y)
                    line_loc.append(point_loc)
                item["data"] = line_loc
                result_data.append(item)
        return JsonResponse({"data_info": result_data})


# 处理PPT： url('^parse_ppt/$', PPTParse.as_view()),
class PPTParse(View):

    # 接收文件名，返回算法数据
    def put(self, request):

        print("我开始进行计算了！")

        return_items = self.parse_calculate(request)
        return JsonResponse({"status": 200, "msg": "OK！", "data": return_items})

    # 接受base64，返回PPT地址
    def post(self, request):
        body = request.body.decode()
        items = json.loads(body)
        try:
            # TODO： 处理PPT的时候，需要用户选择 所有 正确的 文件
            ppt_path = ParsePPT(items).run()
            pprint(ppt_path)
            return JsonResponse({"status": 200, "path": ppt_path})
        except Exception as e:
            return JsonResponse({"status": 404, "msg": "当前访问出错，请联系超级管理员！"})

    # 接受需要下载的文件地址，返回文件信息
    def get(self, request):
        ppt_path = request.GET.get("path")
        file_name = re.search(r'.*/PPTModel/(.*\.pptx)', ppt_path).group(1)

        def file_iterator(file_path, chunk_size=512):
            """
            文件生成器,防止文件过大，导致内存溢出
            :param file_path: 文件绝对路径
            :param chunk_size: 块大小
            :return: 生成器
            """
            with open(file_path, mode='rb') as f:
                while True:
                    count = f.read(chunk_size)
                    if count:
                        yield count
                    else:
                        break

        try:
            response = StreamingHttpResponse(file_iterator(ppt_path))
            response['Content-Type'] = 'application/octet-stream'
            from django.utils.http import urlquote
            response['Content-Disposition'] = 'attachment;filename="%s"' % (urlquote(file_name))
        except:
            return HttpResponse("Sorry but Not Found the File")
        return response

    # 返回分段取峰值
    def patch(self, request):
        """
        分段去峰值的时候，只接受数据本身，需要先进行算法计算，然后获取当前的结果
        处理数据本身的时候，应该选择x=0-1000，这个范围内获取最大值，而不是隔1000取点
        返回数据的同时，携带当前数据中的文件信息（文件名，通道信息，取点范围）
        """
        result_list = []
        body = request.body
        body_str = body.decode()
        body_json = json.loads(body_str)
        # print(body_json)
        calculate_name = body_json["calculate_name"]
        range_key = int(body_json["step"])
        refer_channel = body_json["refer_channel"]
        rpm_type = 'rising'  # 设置rpm_type的默认值
        for children_file in body_json["children"]:  # 前端发送的数据通道不止一条
            # 获取文件信息
            filename = children_file["title"]

            return_items = {}
            return_items["data"] = []
            return_items["filename"] = filename
            status = Fileinfo.objects.filter(file_name=filename)

            i = 1
            children_list = []
            for channel in children_file["children"]:
                children_list.append({"id": i, "title": channel["title"]})
                i += 1

            if len(status) > 0:
                status = status[0].status
                if status in FALLING_LIST:
                    rpm_type = 'falling'

                data = {
                    "calculate": calculate_name,
                    "file_info": {
                        "checked": "True",
                        "children": [{"children": children_list, "id": 1, "title": filename}, ],
                        "field": "name1",
                        "id": 1,
                        "spread": "True",
                        "title": "文件夹名"
                    }
                }
                # pprint(data)
                try:
                    items = ParseTask(data, rpm_type, refer_channel).user_run()
                    # print(items)
                    if items:
                        for item in items:
                            line_loc = [[x, y] for x, y in zip(
                                list(item["data"]["X"]),
                                list(item["data"]["Y"])
                            )]  # 所有点的列表

                            # 对所有点的列表进行分段取峰值
                            # 通过 X的值的间隔 取值
                            x_list = list(map(lambda k: k[0], line_loc))
                            point_index_list = parse(x_list, range_key)
                            point_index_list.append(line_loc[0][0])

                            point_max_list = []
                            for i in range(len(sorted(point_index_list)) - 1):
                                i_in_x_index_2 = x_list.index(point_index_list[i])
                                i_in_x_index_1 = x_list.index(point_index_list[i - 1])

                                segment_list = line_loc[i_in_x_index_1:i_in_x_index_2]
                                if i == 0:
                                    segment_list = line_loc[0:i_in_x_index_2]
                                # print(i, len(segment_list), segment_list)

templates/base_update.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="{% static 'plugin/layui/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'plugin/layui/style/admin.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'plugin/layui/style/login.css' %}" media="all">
    <link id="layuicss-layer" rel="stylesheet" href="{% static 'plugin/layui/style/layer.css' %}" media="all">
    <style>
        .layui-nav * {
            font-size: 20px;
        }
    </style>
</head>
<body class="layui-layout-body">

<div id="LAY_app">
    <div class="layui-layout layui-layout-admin">
        <div class="layui-header">
            <!-- 头部区域 -->
            <ul class="layui-nav layui-layout-left">
                <li class="layui-nav-item layadmin-flexible" lay-unselect>
                    <a href="javascript:;" layadmin-event="flexible" title="侧边伸缩">
                        <i class="layui-icon layui-icon-shrink-right" id="LAY_app_flexible"></i>
                    </a>
                </li>
                <li class="layui-nav-item layui-hide-xs" lay-unselect>
                    <a href="http://192.168.43.111:8899" target="_blank" title="前台">
                        <i class="layui-icon layui-icon-website"></i>
                    </a>
                </li>
                <li class="layui-nav-item" lay-unselect>
                    <a href="javascript:;" layadmin-event="refresh" title="刷新">
                        <i class="layui-icon layui-icon-refresh-3"></i>
                    </a>
                </li>
                <li class="layui-nav-item layui-hide-xs" lay-unselect>
                    <input type="text" placeholder="搜索..." autocomplete="off" class="layui-input layui-input-search" layadmin-event="serach" lay-action="template/search.html?keywords=">
                </li>
            </ul>
            <ul class="layui-nav layui-layout-right" lay-filter="layadmin-layout-right">

                <li class="layui-nav-item" lay-unselect>
{#                    <a lay-href="{% static 'plugin/layui/tpl/system/message.html' %}" layadmin-event="message" lay-text="消息中心">#}
                    <a lay-href="{{ "users:home" }}" layadmin-event="message" lay-text="消息中心">
                        <i class="layui-icon layui-icon-notice"></i>

                        <!-- 如果有新消息，则显示小圆点 -->
                        <span class="layui-badge-dot"></span>
                    </a>
                </li>
                <li class="layui-nav-item layui-hide-xs" lay-unselect>
                    <a href="javascript:;" layadmin-event="theme">
                        <i class="layui-icon layui-icon-theme"></i>
                    </a>
                </li>
                <li class="layui-nav-item layui-hide-xs" lay-unselect>
                    <a href="javascript:;" layadmin-event="note">
                        <i class="layui-icon layui-icon-note"></i>
                    </a>
                </li>
                <li class="layui-nav-item layui-hide-xs" lay-unselect>
                    <a href="javascript:;" layadmin-event="fullscreen">
                        <i class="layui-icon layui-icon-screen-full"></i>
                    </a>
                </li>
                <li class="layui-nav-item" lay-unselect>
                    <a href="javascript:;">
                        <cite>贤心</cite>
                    </a>
                    <dl class="layui-nav-child">
                        <dd><a lay-href="{% static 'plugin/layui/tpl/system/info.html' %}">基本资料</a></dd>
                        <dd><a lay-href="set/user/password.html">修改密码</a></dd>
                        <hr>
                        {#                        <dd layadmin-event="logout" style="text-align: center;"><a>退出</a></dd>#}
                        <dd layadmin-event="" style="text-align: center;"><a href="{% url 'users:logout' %}">退出</a></dd>
                    </dl>
                </li>

                <li class="layui-nav-item layui-hide-xs" lay-unselect>
                    <a href="javascript:;" layadmin-event="about"><i class="layui-icon layui-icon-more-vertical"></i></a>
                </li>
                <li class="layui-nav-item layui-show-xs-inline-block layui-hide-sm" lay-unselect>
                    <a href="javascript:;" layadmin-event="more"><i class="layui-icon layui-icon-more-vertical"></i></a>
                </li>
            </ul>
        </div>

        <!-- 侧边菜单 -->
        <div class="layui-side layui-side-menu">
            <div class="layui-side-scroll">
                <div class="layui-logo" lay-href="{% static 'plugin/layui/tpl/system/console.html' %}">
                    <span>layuiAdmin</span>
                </div>

                <ul class="layui-nav layui-nav-tree" lay-shrink="all" id="LAY-system-side-menu" lay-filter="layadmin-system-side-menu">
                    <li data-name="home" class="layui-nav-item layui-nav-itemed">
                        <a lay-href="/user/home/" lay-tips="主页" lay-direction="2">
                            <i class="layui-icon layui-icon-home"></i>
                            <cite>&nbsp;&nbsp;&nbsp;&nbsp;主页</cite>
                        </a>
                    </li>
                    <li data-name="component" class="layui-nav-item">
                        <a href="/test/upload/" lay-tips="组件" lay-direction="2">
                            <i class="layui-icon layui-icon-component"></i>
                            <cite>&nbsp;&nbsp;&nbsp;&nbsp;上传</cite>
                        </a>
                    </li>
                    <li data-name="template" class="layui-nav-item">
                        <a href="/test/datainfo/" lay-tips="页面" lay-direction="2">
                            <i class="layui-icon layui-icon-template"></i>
                            <cite>&nbsp;&nbsp;&nbsp;&nbsp;检索</cite>
                        </a>
                        <dl class="layui-nav-child">
                            <dd><a :href="'/test/datainfo/'+ platform.id">&nbsp;&nbsp;&nbsp;[[ platform.name ]]</a></dd>
                        </dl>
                    </li>
                    <li data-name="app" class="layui-nav-item">
                        <a lay-href="/calculate/parse/" lay-tips="应用" lay-direction="2">
                            <i class="layui-icon layui-icon-app"></i>
                            <cite>&nbsp;&nbsp;&nbsp;&nbsp;分析</cite>
                        </a>
                    </li>
                    <li data-name="senior" class="layui-nav-item">
                        <a lay-href="javascript:;" lay-tips="高级" lay-direction="2">
                            <i class="layui-icon layui-icon-senior"></i>
                            <cite>&nbsp;&nbsp;&nbsp;&nbsp;挖掘</cite>
                        </a>
                    </li>
                    <li data-name="user" class="layui-nav-item">
                        <a href="javascript:;" lay-tips="用户" lay-direction="2">
                            <i class="layui-icon layui-icon-user"></i>
                            <cite>&nbsp;&nbsp;&nbsp;&nbsp;抱怨</cite>
                        </a>
                        <dl class="layui-nav-child">
                            <dd><a lay-href="user/user/list.html">&nbsp;&nbsp;&nbsp;&nbsp;上传</a></dd>
                            <dd><a lay-href="user/administrators/list.html">&nbsp;&nbsp;&nbsp;&nbsp;检索</a></dd>
                        </dl>
                    </li>
                    <li data-name="set" class="layui-nav-item">
                        <a href="javascript:;" lay-tips="设置" lay-direction="2">
                            <i class="layui-icon layui-icon-set"></i>
                            <cite>&nbsp;&nbsp;&nbsp;&nbsp;音频</cite>
                        </a>
                        <dl class="layui-nav-child">
                            <dd><a lay-href="user/user/list.html">&nbsp;&nbsp;&nbsp;&nbsp;上传</a></dd>
                            <dd><a lay-href="user/administrators/list.html">&nbsp;&nbsp;&nbsp;&nbsp;检索</a></dd>
                            <dd><a lay-href="user/administrators/list.html">&nbsp;&nbsp;&nbsp;&nbsp;对比</a></dd>
                        </dl>
                    </li>
                    <li data-name="get" class="layui-nav-item">
                        <a href="/script/info" lay-href="" lay-tips="授权" lay-direction="2">
                            <i class="layui-icon layui-icon-auz"></i>
                            <cite>&nbsp;&nbsp;&nbsp;&nbsp;脚本</cite>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- 页面标签 -->
        <div class="layadmin-pagetabs" id="LAY_app_tabs">
            <div class="layui-icon layadmin-tabs-control layui-icon-prev" layadmin-event="leftPage"></div>
            <div class="layui-icon layadmin-tabs-control layui-icon-next" layadmin-event="rightPage"></div>
            <div class="layui-icon layadmin-tabs-control layui-icon-down">
                <ul class="layui-nav layadmin-tabs-select" lay-filter="layadmin-pagetabs-nav">
                    <li class="layui-nav-item" lay-unselect>
                        <a href="javascript:;"></a>
                        <dl class="layui-nav-child layui-anim-fadein">
                            <dd layadmin-event="closeThisTabs"><a href="javascript:;">关闭当前标签页</a></dd>
                            <dd layadmin-event="closeOtherTabs"><a href="javascript:;">关闭其它标签页</a></dd>
                            <dd layadmin-event="closeAllTabs"><a href="javascript:;">关闭全部标签页</a></dd>
                        </dl>
                    </li>
                </ul>
            </div>
            <div class="layui-tab" lay-unauto lay-allowClose="true" lay-filter="layadmin-layout-tabs">
                <ul class="layui-tab-title" id="LAY_app_tabsheader">
                    <li lay-id="{% static 'plugin/layui/tpl/system/console.html' %}" lay-attr="{% static 'plugin/layui/tpl/system/console.html' %}" class="layui-this"><i class="layui-icon layui-icon-home"></i></li>
                </ul>
            </div>
        </div>

        <!-- 主体内容 -->
        <div class="layui-body" id="LAY_app_body">
            <div class="layadmin-tabsbody-item layui-show">
                <iframe src="{% static 'plugin/layui/tpl/system/homepage1.html' %}" frameborder="0" class="layadmin-iframe"></iframe>
            </div>
        </div>

        <!-- 辅助元素，一般用于移动设备下遮罩 -->
        <div class="layadmin-body-shade" layadmin-event="shade"></div>
    </div>
</div>


<script src="{% static 'js/axios-0.18.0.min.js' %}"></script>
<script src="{% static 'js/jquery-3.4.1.js' %}"></script>
<script src="{% static 'plugin/layui/layui.js' %}"></script>
<script src="{% static 'js/vue_2.6.10.js' %}"></script>
<script>
    layui.config({
        base: "{% static 'plugin/layui/' %}"
    }).extend({
        index: 'lib/index' //主入口模块
    }).use('index');
</script>
<script>
    var vm = new Vue({
        el: "#user_info",
        delimiters: ['[[', ']]'],
        data: {
            user_id: sessionStorage.user_id || localStorage.user_id,
            token: sessionStorage.token || localStorage.token,
            username: sessionStorage.username || localStorage.username,
            job_number: sessionStorage.job_number || localStorage.job_number,
            worktime: sessionStorage.worktime || localStorage.worktime,
        },
        mounted: function () {
            // 判断用户的登录状态
            if (this.user_id && this.token && this.username) {
                axios.get('/user/user/' + user_id, {
                    // 向后端传递JWT token的方法
                    headers: {
                        'Authorization': 'JWT ' + this.token
                    },
                    responseType: 'json',
                    withCredentials: true
                })
                    .then(response => {
                        // 加载用户数据
                        this.user_id = response.data.id;
                        this.job_number = response.data.job_number;
                        this.username = response.data.username;
                        this.worktime = response.data.worktime;
                    })
                    .catch(error => {
                        {#if (error.response.status == 401 || error.response.status == 403) {#}
                        {#    location.href = {% static login_2.html %};#}

                    });
            } else {
                location.href = '/user/home/';
            }
        },
        methods: {
            // 登录
            login: function () {
                location.href = '/user/login/';
            },
            // 退出
            logout: function () {
                sessionStorage.clear();
                localStorage.clear();
                location.href = '/user/logout/';
            },
        }
    })
</script>

{% block javascript %}{% endblock %}


</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}HOME{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static '/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui/css/admin.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui/css/modules/layer/default/layer.css' %}">
{% endblock %}

{% block content %}
    <div class="layui-fluid" id="layui-fluid" style="padding:15px">
        <h3>[[ job_number ]]</h3>
        <h3>[[ username ]]</h3>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        layui.config({
            base: '{% static '/home/' %}' //静态资源所在路径
        }).use('index', function () {
            var layer = layui.layer,
                admin = layui.admin,
                element = layui.element;
        });
    </script>

    <!-- 绑定用户信息 -->
    <!--<script>
    var vm = new Vue({
        el: "#layui-fluid",
        // el: "#LAY_app",
        delimiters: ['[[', ']]'],
        data: {
            user_id: sessionStorage.user_id || localStorage.user_id,
            token: sessionStorage.token || localStorage.token,
            username: '',
            job_number: '',
        },
        mounted: function () {
            // 判断用户的登录状态
            if (this.user_id && this.token) {
                axios.get('/user/', {
                    // 向后端传递JWT token的方法
                    headers: {
                        'Authorization': 'JWT ' + this.token
                    },
                    responseType: 'json',
                    withCredentials: true
                })
                    .then(response => {
                        // 加载用户数据
                        this.user_id = response.data.id;
                        this.job_number = response.data.job_number;
                        this.username = response.data.username;
                    })
                    .catch(error => {
                        if (error.response.status == 401 || error.response.status == 403) {
                            location.href = '../../../epgn_front_end/login_2.html';
                        }
                    });
            } else {
                location.href = '../../../epgn_front_end/login_2.html';
            }
        },
        methods: {
            // 登录
            login: function () {
                location.href = '../../../epgn_front_end/login_2.html';
            },
            // 退出
            logout: function () {
                sessionStorage.clear();
                localStorage.clear();
                location.href = '../../../epgn_front_end/login_2.html';
            },
        }
    })
</script>-->

{% endblock %}